name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - affine=2.3.0
  - aiohttp=3.7.4
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.9.1
  - antlr-python-runtime=4.7.2
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - asteval=0.9.23
  - astroid=2.3.3
  - astropy=4.2.1
  - async-timeout=3.0.1
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.2
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.3
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - bitarray=1.9.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - bokeh=2.0.1
  - boost-cpp=1.72.0
  - boto=2.49.0
  - boto3=1.16.4
  - botocore=1.19.63
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2020.12.5
  - cf-units=2.1.4
  - cffi=1.14.5
  - cfgrib=0.9.9.0
  - cfitsio=3.470
  - cftime=1.1.3
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - comtypes=1.1.9
  - conda=4.10.1
  - conda-build=3.18.9
  - conda-env=2.6.0
  - conda-package-handling=1.7.2
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextily=1.0.0
  - contextlib2=0.6.0.post1
  - coverage=5.4
  - cryptography=3.4.7
  - curl=7.76.0
  - cx_oracle=7.0.0
  - cycler=0.10.0
  - cython=0.29.22
  - cytoolz=0.11.0
  - dask=2.15.0
  - dask-core=2.15.0
  - dask-gateway=0.9.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - deprecated=1.2.10
  - descartes=1.1.0
  - diff-match-patch=20200713
  - distributed=2.26.0
  - docutils=0.17
  - eccodes=2.18.0
  - elementpath=2.0.5
  - emcee=3.0.2
  - entrypoints=0.3
  - enum34=1.1.10
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - fastcache=1.1.0
  - filelock=3.0.12
  - fiona=1.8.13
  - flake8=3.7.9
  - flask=1.1.2
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=0.9.0
  - future=0.18.2
  - gdal=3.0.4
  - geographiclib=1.50
  - geopandas=0.8.2
  - geoplot=0.4.1
  - geopy=1.20.0
  - geos=3.8.1
  - geotiff=1.5.1
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=21.1.2
  - git=2.26.2
  - gitdb=4.0.7
  - gitdb2=4.0.2
  - gitpython=3.1.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - glob2=0.7
  - gmpy2=2.1.0b1
  - graphviz=2.38.0
  - greenlet=1.0.0
  - h5py=3.2.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - html5lib=1.1
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - importlib_resources=5.1.2
  - iniconfig=1.1.1
  - intel-openmp=2021.1.2
  - intervaltree=3.0.2
  - ipykernel=5.5.3
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.15.2
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.1
  - jupyter_console=6.1.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=2.3.1
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.14
  - keyring=23.0.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=9.0.1
  - libcurl=7.76.0
  - libffi=3.3
  - libgdal=3.0.4
  - libglib=2.68.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblief=0.10.1
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.15.7
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvmlite=0.36.0
  - lmfit=1.0.0
  - locket=0.2.0
  - lxml=4.6.3
  - lz4-c=1.9.2
  - lzo=2.10
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.2.0
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mercantile=1.1.6
  - metpy=1.0
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.0
  - mock=4.0.3
  - more-itertools=8.7.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - munch=2.5.0
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - nbstripout=0.3.7
  - netcdf4=1.5.6
  - networkx=2.5.1
  - nltk=3.5
  - nose=1.3.7
  - notebook=6.1.4
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.20.2
  - numpy-base=1.18.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - owslib=0.18.0
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.5.2
  - partd=1.1.0
  - path=15.1.2
  - path.py=12.5.0
  - pathlib=1.0.1
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pbr=5.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pint=0.17
  - pip=21.0.1
  - pkginfo=1.7.0
  - pluggy=0.13.1
  - ply=3.11
  - pooch=1.3.0
  - poppler=0.67.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - powershell_shortcut=0.0.1
  - proj=7.0.0
  - prometheus_client=0.10.0
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - protobuf=3.15.7
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydocstyle=6.0.0
  - pydot=1.4.1
  - pyepsg=0.4.0
  - pyerfa=1.7.2
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pykdtree=1.3.4
  - pylint=2.4.4
  - pynacl=1.4.0
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.6
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pyside2=5.13.2
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.3
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-eccodes=2021.03.0
  - python-graphviz=0.14
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.10
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2021.1
  - pywavelets=1.1.1
  - pywin32=300
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - qdarkstyle=3.0.2
  - qt=5.12.5
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - rasterio=1.1.5
  - regex=2021.4.4
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.80
  - s3transfer=0.3.6
  - schwimmbad=0.3.2
  - scikit-image=0.18.1
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - shapely=1.7.0
  - simplegeneric=0.8.1
  - singledispatch=3.6.1
  - sip=4.19.25
  - siphon=0.8.0
  - six=1.15.0
  - smmap=3.0.5
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - snuggs=1.4.7
  - sortedcollections=2.1.0
  - sortedcontainers=2.3.0
  - soupsieve=2.0.1
  - sphinx=3.0.3
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.1
  - spyder-kernels=1.9.0
  - sqlalchemy=1.4.5
  - sqlite=3.35.4
  - statsmodels=0.11.1
  - sympy=1.7.1
  - tbb=2020.2
  - tblib=1.7.0
  - tendo=0.2.15
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2019.7.26.2
  - tiledb=1.7.7
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - udunits2=2.2.27.27
  - ujson=1.35
  - uncertainties=3.1.5
  - unicodecsv=0.14.1
  - urllib3=1.25.7
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - watchdog=2.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xarray=0.17.0
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xlsxwriter=1.3.8
  - xlwings=0.23.0
  - xlwt=1.3.0
  - xmlschema=1.3.1
  - xz=5.2.5
  - yaml=0.2.4
  - yapf=0.30.0
  - yarl=1.6.3
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.3.0
  - zstd=1.4.4
  - pip:
    - cartopy==0.18.0
    - pydeps==1.8.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - sharppy==1.4.0b1+8.ga7f73dbe.dirty
    - snakefood==1.4
    - stdlib-list==0.5.0
